name: Node CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pr:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

